ljhpaul/cardgarden

- src/main/resources/mysqlDB.properties
- src/main/webapp/WEB-INF/views/common/header.jsp
- src/main/webapp/resources/css/header.css
- src/main/webapp/resources/js/header.js
스크롤 내리면 nav bar 이동하게 수정했습니다~
close #3
> 움직이는 sticky 바 구현 완료

- src/main/webapp/WEB-INF/views/common/header.jsp
> feature: 주소설정

- src/main/webapp/WEB-INF/views/common/header.jsp
- src/main/webapp/resources/css/header.css
> style: 링크와 기타 css 수정

- src/main/webapp/resources/css/header.css
- src/main/webapp/resources/js/header.js
> style:헤더 패딩 진짜 완료 ^_^

- src/main/resources/mybatis/mappers/cardDetailMapper.xml
- src/main/resources/mybatis/mappers/cardSearchConditionMapper.xml
- src/main/resources/mybatis/sqlMapConfig.xml
> fix: dto 중복 별칭 해결

- src/main/java/com/cardgarden/project/controller/user/JoinController.java
- src/main/webapp/WEB-INF/views/join/inputInfo.jsp
- src/main/webapp/WEB-INF/views/join/termAgree.jsp
- src/main/webapp/WEB-INF/views/join/verifyEmail.jsp
> feat: 회원정보 입력 구현중

- src/main/java/com/cardgarden/project/controller/user/LoginController.java
- src/main/webapp/WEB-INF/views/common/header.jsp
- src/main/webapp/WEB-INF/views/login/loginForm.jsp
- src/main/webapp/resources/css/style.css
> style: 로그인창 디자인 완성

- .gitignore
> docs: .gitignore DB정보 추가

- src/main/java/com/cardgarden/project/controller/user/FindIdController.java
- src/main/java/com/cardgarden/project/controller/user/FindPasswordController.java
- src/main/webapp/WEB-INF/views/login/findIdByName.jsp
- src/main/webapp/WEB-INF/views/login/findIdComplete.jsp
- src/main/webapp/WEB-INF/views/login/findPwdById.jsp
- src/main/webapp/WEB-INF/views/login/findPwdComplete.jsp
- src/main/webapp/WEB-INF/views/login/verifyEmailForFind.jsp
feat: 아이디/비밀번호 찾기용 controller 생성
> feat: 아이디/비밀번호 찾기용 controller 생성

- .gitignore
> fix: gitignore 추가

- src/main/java/com/cardgarden/project/controller/UserConsumptionPatternController.java
- src/main/webapp/WEB-INF/views/cardSearchcondition/insertUserConsumptionPattern.jsp
> fix: 소비패턴 오류 수정

- python/code/.ipynb_checkpoints/card_detail_recommend-checkpoint.py
- python/code/card_detail_recommend.py
- python/code/card_recommend.py
> fix: AI 정확도 안정화

- src/main/java/com/cardgarden/project/controller/user/UserController.java
- src/main/webapp/WEB-INF/views/custom/makeBackground.jsp
- src/main/webapp/resources/css/customMakeBackground.css
- src/main/webapp/resources/css/customMakeFrame.css
> fix: 페이지로 이동하게 완료

- src/main/webapp/WEB-INF/views/mypage/mypage.jsp
> fix: 마이페이지 주소 버그 수정

- src/main/java/com/cardgarden/project/controller/auth/AuthController.java
- src/main/java/com/cardgarden/project/controller/user/UserController.java
- src/main/java/com/cardgarden/project/model/user/service/UserInfoService.java
- src/main/resources/sql/ddl/schema.sql
- src/main/webapp/WEB-INF/views/auth/verifyEmail.jsp
- src/main/webapp/WEB-INF/views/join/inputInfo.jsp
- src/main/webapp/WEB-INF/views/join/inputInfo2.jsp
- src/main/webapp/WEB-INF/views/login/findIdByName.jsp
- src/main/webapp/WEB-INF/views/login/findIdSuccess.jsp
- src/main/webapp/WEB-INF/views/login/findPwdById.jsp
- src/main/webapp/WEB-INF/views/login/findPwdSuccess.jsp
- src/main/webapp/WEB-INF/views/login/loginForm.jsp
- src/main/webapp/WEB-INF/views/mypage/mypage.jsp
- src/main/webapp/resources/css/userStyle.css
> feat: 마이페이지 로직 수정

- src/main/webapp/WEB-INF/views/common/header.jsp
- src/main/webapp/resources/css/header.css
> style: 헤더 하트 표시 변경

- src/main/webapp/WEB-INF/views/common/header.jsp
> fix: 세션 40초 설정

- src/main/java/com/cardgarden/project/controller/card/detail/CardDetailController.java
- src/main/java/com/cardgarden/project/controller/user/LoginController.java
- src/main/resources/sql/ddl/schema.sql
- src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- src/main/webapp/WEB-INF/views/join/inputInfo.jsp
- src/main/webapp/WEB-INF/views/mypage/mycard.jsp
- src/main/webapp/WEB-INF/views/mypage/myconsumptionPattern.jsp
- src/main/webapp/WEB-INF/views/mypage/mypage.jsp
- src/main/webapp/WEB-INF/views/mypage/sidebar.jsp
- src/main/webapp/resources/css/header.css
- src/main/webapp/resources/css/userStyle.css
> feat: 마이페이지 개선

- src/main/java/com/cardgarden/project/controller/user/FindPasswordController.java
- src/main/java/com/cardgarden/project/model/user/dao/UserInfoDAO.java
- src/main/java/com/cardgarden/project/model/user/service/UserInfoService.java
- src/main/resources/mybatis/mappers/userInfoMapper.xml
- src/main/webapp/WEB-INF/views/login/findPwdReset.jsp
> feat: 비밀번호 재설정 구현 완료

- src/main/webapp/WEB-INF/views/login/findPwdReset.jsp
- src/main/webapp/WEB-INF/views/recommend/ai.jsp
> fix: 비밀번호 재설정 개선

- src/main/java/com/cardgarden/project/controller/user/JoinController.java
- src/main/webapp/WEB-INF/views/join/inputInfo.jsp
> feat: 구글 로그인/회원가입 완료

- src/main/java/com/cardgarden/project/controller/event/AttendanceController.java
- src/main/java/com/cardgarden/project/controller/user/LoginController.java
- src/main/webapp/WEB-INF/views/login/loginForm.jsp
> feat: 로그인 성공 후 리다이렉트 분기

- src/main/java/com/cardgarden/project/controller/custom/CustomAssetController.java
- src/main/java/com/cardgarden/project/controller/custom/CustomMakeController.java
- src/main/webapp/WEB-INF/views/common/400.jsp
- src/main/webapp/WEB-INF/views/common/500.jsp
- src/main/webapp/WEB-INF/views/custom/makeFrame.jsp
- src/main/webapp/WEB-INF/web.xml
fix:에러페이지 수정, 커스텀 frame 리다이렉트 완료
> fix:에러페이지 수정, 커스텀 frame 리다이렉트 완료

- .gitignore
> feat: gitignore 하나 추가

- src/main/webapp/WEB-INF/views/main.jsp
> style: 메인페이지 꾸미기

- src/main/webapp/WEB-INF/views/card/cardDetail.jsp
> fix: 전월실적 금액 오류

- src/main/java/com/cardgarden/project/model/cardDetail/CardDetailDTO.java
- src/main/webapp/WEB-INF/views/card/cardDetail.jsp
> fix: 카드 디테일 줄바꿈 수정

- src/main/webapp/WEB-INF/views/card/cardDetail.jsp
- src/main/webapp/WEB-INF/views/recommend/insertUserConsumptionPattern.jsp
- src/main/webapp/resources/css/cardDetail.css
fix : cardDetail.jsp 혜택계산기 버튼 css 수정
> fix : cardDetail.jsp 혜택계산기 버튼 css 수정

- src/main/webapp/WEB-INF/views/login/findPwdReset.jsp
> feat: 비밀번호 재설정 개선

- src/main/webapp/WEB-INF/views/recommend/insertUserConsumptionPattern.jsp
> fix : 충돌 css 수정

- src/main/webapp/WEB-INF/views/recommend/ai.jsp
> style: ai 추천 margin 변경

- src/main/resources/mybatis/mappers/cardSearchConditionMapper.xml
- src/main/webapp/WEB-INF/views/cardSearchcondition/cardSearchcondition.jsp
> fix : 대카테고리 선택 시 버그 수정

- python/code/card_recommend_total.py
- src/main/webapp/WEB-INF/views/recommend/insertUserConsumptionPattern.jsp
> fix: 혜택 계산기 url 충돌 해결

- src/main/java/com/cardgarden/project/controller/card/detail/CardDetailController.java
> fix: 혜택 계산기 비로그인일떄도 가능하게 수정

- src/main/webapp/WEB-INF/views/card/cardDetail.jsp
- src/main/webapp/WEB-INF/views/recommend/aiPattern.jsp
- src/main/webapp/resources/css/cardDetail.css
> style: 카드 상세보기 페이지 수정

- pom.xml
fix: pom.xml jdk버전 수정 및 .sql 파일 업로드
> fix: pom.xml jdk버전 수정 및 .sql 파일 업로드

- pom.xml
> fix: pom.xml 빌드명 수정

- pom.xml
> fix: pom.xml 수정

- pom.xml
> fix: pom.xml name 수정

- src/main/webapp/WEB-INF/web.xml
> docs: .sql edit

- src/main/resources/mybatis/mappers/cardRankMapper.xml
> fix: card 대문자 수정

- python/code/card_recommend_total.py
- python/code/requirements.txt
> fix: python 배포 준비 완료

- python/code/card_recommend_total.py
> fix: ai 시간 조절

- python/code/card_recommend_total_v0.1.py
> fix: python version 0.1 추가
